// <auto-generated />
using System;
using BNHomeAllocation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BnHomeAllocationApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BnHomeAllocationApp.Models.ApplicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ApplicationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Special Consideration"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NAM"
                        });
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.BuildingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("BuildingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A Type"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B Type"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C Type"
                        });
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CommissionDate");

                    b.Property<string>("CurrentWorkPlace");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfChildren");

                    b.Property<int>("OfficerRankId");

                    b.Property<string>("PNO");

                    b.HasKey("Id");

                    b.HasIndex("OfficerRankId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.OfficerRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("RankPoint");

                    b.HasKey("Id");

                    b.ToTable("OfficerRanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admiral",
                            RankPoint = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vice Admiral",
                            RankPoint = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rear Admiral",
                            RankPoint = 15
                        },
                        new
                        {
                            Id = 4,
                            Name = "Commodore",
                            RankPoint = 9
                        },
                        new
                        {
                            Id = 5,
                            Name = "Captain",
                            RankPoint = 7
                        },
                        new
                        {
                            Id = 6,
                            Name = "Commander",
                            RankPoint = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lieutenant Commander",
                            RankPoint = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lieutenant",
                            RankPoint = 0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sub Lieutenant",
                            RankPoint = 0
                        });
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.OfficerResidenceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AllottementDate");

                    b.Property<DateTime>("ApplicationDate");

                    b.Property<int?>("ApplicationTypeId");

                    b.Property<bool>("HasAppliedForResidence");

                    b.Property<bool>("HasAppliedForResidenceChange");

                    b.Property<bool>("IsAllotted");

                    b.Property<bool>("IsVancancyProbable");

                    b.Property<DateTime>("JoiningDate");

                    b.Property<int>("OfficerId");

                    b.Property<string>("Preference");

                    b.Property<DateTime>("ProbableVacancyDate");

                    b.Property<string>("Reason");

                    b.Property<string>("Remarks");

                    b.Property<int?>("ResidenceId");

                    b.Property<DateTime>("VacancyDate");

                    b.Property<string>("VacancyReason");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationTypeId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("OfficerResidenceInfoes");
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.Residence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details");

                    b.Property<bool>("IsAllotted");

                    b.Property<string>("Name");

                    b.Property<int>("ResidenceBuildingId");

                    b.HasKey("Id");

                    b.HasIndex("ResidenceBuildingId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAllotted = false,
                            Name = "Bungalow A/1",
                            ResidenceBuildingId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsAllotted = false,
                            Name = "Bungalow A/2",
                            ResidenceBuildingId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsAllotted = false,
                            Name = "Bungalow A/3",
                            ResidenceBuildingId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsAllotted = false,
                            Name = "108 B/1",
                            ResidenceBuildingId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsAllotted = false,
                            Name = "108 B/2",
                            ResidenceBuildingId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsAllotted = false,
                            Name = "108 B/3",
                            ResidenceBuildingId = 2
                        });
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.ResidenceBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildingTypeId");

                    b.Property<string>("Name");

                    b.Property<int>("ResidenceZoneId");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("ResidenceZoneId");

                    b.ToTable("ResidenceBuildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingTypeId = 1,
                            Name = "Bungalow",
                            ResidenceZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            BuildingTypeId = 2,
                            Name = "10 Storied Building No -108",
                            ResidenceZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            BuildingTypeId = 2,
                            Name = "121 B-1",
                            ResidenceZoneId = 2
                        });
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.ResidenceZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ResidenceZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NHQ Residential Area"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ShaheenBag"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nakhal Para Dhaka"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.Officer", b =>
                {
                    b.HasOne("BnHomeAllocationApp.Models.OfficerRank", "OfficerRank")
                        .WithMany()
                        .HasForeignKey("OfficerRankId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.OfficerResidenceInfo", b =>
                {
                    b.HasOne("BnHomeAllocationApp.Models.ApplicationType", "ApplicationType")
                        .WithMany()
                        .HasForeignKey("ApplicationTypeId");

                    b.HasOne("BnHomeAllocationApp.Models.Officer", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BnHomeAllocationApp.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId");
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.Residence", b =>
                {
                    b.HasOne("BnHomeAllocationApp.Models.ResidenceBuilding", "ResidenceBuilding")
                        .WithMany()
                        .HasForeignKey("ResidenceBuildingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BnHomeAllocationApp.Models.ResidenceBuilding", b =>
                {
                    b.HasOne("BnHomeAllocationApp.Models.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BnHomeAllocationApp.Models.ResidenceZone", "ResidenceZone")
                        .WithMany("ResidenceBuildings")
                        .HasForeignKey("ResidenceZoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
